### PR TITLE
Add a bin script to combine svg files

### PR DESCRIPTION
**Pull request by dpogue**
This allows you to run svgstore as a tool using npm scripts.
### Usage

```
svgstore [-o outputfile] inputfiles
```
- Input files will be parsed using glob, so you can use paths like `**/*.svg`
- By default will output to stdout, but can be directed to a file via `-o outputfile`
#### Examples

```
svgstore *.svg > icons.svg

svgstore *.svg | svgo -i - -o - > icons.min.svg

svgstore -o icons.svg ./assets/icons/**/*.svg

svgstore -o sprites.svg ./tiles/1.svg ./tiles/2.svg ./tiles/3.svg
```

### CODE REVIEW

**Comment by shannonmoeller** [comment]
I'd rather not have this module touch the file system in any way. That's best left to the consumers (gulp, grunt, broccoli, etc.). Would you mind publishing this bin script as a standalone module? Something like `svgstore-cli`?

**Comment by shannonmoeller** [comment]
This would mirror other utils like [`trash`](http://npm.im/trash-cli) and [`trash-cli`](http://npm.im/trash-cli).

And, sorry for not leading with this, thanks for the PR!

**Comment by dpogue** [comment]
Cool, that sounds like a plan. 😃
I'll set up a repo and publish to npm, and then I'm happy to transfer it to the svgstore organization if that's what you prefer.

**Comment by shannonmoeller** [comment]
Great! I created a repo and added you as an admin. Feel free to use it.

https://github.com/svgstore/svgstore-cli

**Pull request closed without merging**
